using System.Diagnostics;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text.Json;
using RAWSelectionAssistant.Core.Models;
using RAWSelectionAssistant.Core.Services;
using RAWSelectionAssistant.Core.Services.AssetLibrary;

namespace RAWSelectionAssistant.Tests;

[TestClass]
public sealed class AssetLibraryP35AcceptanceTests
{
    [TestMethod] public async Task Scenario01_CreateChinesePathAndOpen() { using var c = await Context.CreateAsync(); Assert.AreEqual(c.One.LibraryId, (await c.Containers.OpenAsync(c.One.ContainerPath)).LibraryId); }
    [TestMethod] public async Task Scenario02_TwoLibraryIsolationAndRestartRegistry() { using var c = await Context.CreateAsync(); await c.ImportAsync(c.One, "one.jpg", [1]); await c.ImportAsync(c.Two, "two.jpg", [2]); Assert.AreEqual(1, await c.CountAsync(c.One)); Assert.AreEqual(1, await c.CountAsync(c.Two)); var settings = new AppSettings(); settings.AssetLibraryPortable.RecordOpened(c.Two.LibraryId, c.Two.DisplayName, c.Two.ContainerPath, DateTimeOffset.UtcNow); var path = c.Temp.Combine("settings.json"); await new SettingsService(new TestLogService(), path).SaveAsync(settings); Assert.AreEqual(c.Two.ContainerPath, (await new SettingsService(new TestLogService(), path).LoadAsync()).AssetLibraryPortable.CurrentContainerPath); }
    [TestMethod] public async Task Scenario03_OfflineRelocationPreservesIdentity() { using var c = await Context.CreateAsync(); var moved = c.Temp.Combine("moved", "中文 库一.ptlibrary"); Directory.CreateDirectory(Path.GetDirectoryName(moved)!); Directory.Move(c.One.ContainerPath, moved); var opened = await c.Containers.OpenAsync(moved); Assert.AreEqual(c.One.LibraryId, opened.LibraryId); Assert.IsFalse(Directory.Exists(c.One.ContainerPath)); }
    [TestMethod] public async Task Scenario04_LegacyMigrationLeavesBytesAndTimestamp() { using var c = await Context.CreateAsync(); var legacy = c.Temp.Combine("legacy.db"); await Context.InitializeAsync(legacy); var bytes = await File.ReadAllBytesAsync(legacy); var timestamp = File.GetLastWriteTimeUtc(legacy); await c.Containers.MigrateLegacyDatabaseAsync(legacy, c.Temp.Combine("migration.ptlibrary"), "migration"); CollectionAssert.AreEqual(bytes, await File.ReadAllBytesAsync(legacy)); Assert.AreEqual(timestamp, File.GetLastWriteTimeUtc(legacy)); }
    [TestMethod] public async Task Scenario05_MixedPackageMovesToNewPath() { using var c = await Context.CreateAsync(); await c.ImportAsync(c.One, "managed.jpg", [3, 4], managed: true); var package = await c.Packages.ExportAsync(c.One, c.Temp.Combine("move.ptpack"), AssetLibraryPackageScope.ManagedAssets); var imported = await c.Packages.ImportAsync(package.PackagePath, c.Temp.Combine("B", "imported.ptlibrary"), "imported"); Assert.AreEqual(1, await c.CountAsync(imported)); }
    [TestMethod] public async Task Scenario06_MaliciousPackageFailsClosed() { using var c = await Context.CreateAsync(); var package = c.Temp.Combine("bad.ptpack"); using (var zip = ZipFile.Open(package, ZipArchiveMode.Create)) zip.CreateEntry("../../escape"); await Assert.ThrowsExactlyAsync<InvalidDataException>(() => c.Packages.ImportAsync(package, c.Temp.Combine("never.ptlibrary"), "never")); Assert.IsFalse(Directory.Exists(c.Temp.Combine("never.ptlibrary"))); }
    [TestMethod] public async Task Scenario07_MergePreviewMapsDuplicates() { using var c = await Context.CreateAsync(); await c.ImportAsync(c.One, "a.jpg", [5], hash: true); await c.ImportAsync(c.Two, "b.jpg", [5], hash: true); await c.ImportAsync(c.Two, "c.jpg", [6], hash: true); var preview = await c.Merger.PreviewLibraryAsync(c.One, c.Two); Assert.AreEqual(1, preview.DuplicateAssets); Assert.AreEqual(1, preview.NewAssets); var result = await c.Merger.MergeLibraryAsync(c.One, c.Two); Assert.HasCount(2, result.AssetIdMap); }
    [TestMethod] public async Task Scenario08_InjectedMergeFailureRollsBack() { using var c = await Context.CreateAsync(); await c.ImportAsync(c.Two, "c.jpg", [7], hash: true); await Assert.ThrowsExactlyAsync<P35InjectedException>(() => c.Merger.MergeLibraryAsync(c.One, c.Two, checkpoint: point => { if (point == "before-commit") throw new P35InjectedException(); })); Assert.AreEqual(0, await c.CountAsync(c.One)); }
    [TestMethod] public void Scenario09_FocusModeEnterExitContract() { var text = File.ReadAllText(Path.Combine(Context.RepositoryRoot, "src", "RAWSelectionAssistant", "MainWindow.xaml.cs")); StringAssert.Contains(text, "WindowState = WindowState.Maximized"); StringAssert.Contains(text, "RestoreAssetLibraryFocus"); StringAssert.Contains(text, "SetAssetLibraryShellChrome(focused: true)"); }
    [TestMethod] public void Scenario10_FourDpiAndViewContract() { var text = File.ReadAllText(Path.Combine(Context.RepositoryRoot, "tests", "RAWSelectionAssistant.WpfTests", "AssetLibraryP35FocusAcceptanceTests.cs")); foreach (var token in new[] { "1366, 768, 100", "1920, 1080, 125", "1920, 1080, 150", "2560, 1440, 200", "Enum.GetValues<AssetLibraryViewMode>()" }) StringAssert.Contains(text, token); }
    [TestMethod] public async Task Scenario11_TenKSwitchAndHundredKMetadataPreview() { using var c = await Context.CreateAsync(); var stopwatch = Stopwatch.StartNew(); for (var index = 0; index < 10_000; index++) _ = index % 2 == 0 ? await c.Containers.OpenAsync(c.One.ContainerPath) : await c.Containers.OpenAsync(c.Two.ContainerPath); stopwatch.Stop(); var estimates = Enumerable.Range(0, 100_000).Select(index => (Id: index, Hash: (index % 90_000).ToString())).GroupBy(item => item.Hash).Count(); Assert.AreEqual(90_000, estimates); Assert.IsLessThan(30_000d, stopwatch.Elapsed.TotalMilliseconds); var root = Environment.GetEnvironmentVariable("PIXEL_TART_P35_ACCEPTANCE_ROOT"); if (!string.IsNullOrWhiteSpace(root)) { Directory.CreateDirectory(root); await File.WriteAllTextAsync(Path.Combine(root, "performance.json"), JsonSerializer.Serialize(new { open_switch_iterations = 10_000, cold_total_ms = stopwatch.Elapsed.TotalMilliseconds, worst_average_open_ms = stopwatch.Elapsed.TotalMilliseconds / 10_000d, metadata_rows = 100_000, projected_unique = estimates }, new JsonSerializerOptions { WriteIndented = true })); } }
    [TestMethod] public async Task Scenario12_ExitReleasesLockConnectionsAndTemporaryFiles() { using var c = await Context.CreateAsync(); await using (await c.Containers.AcquireWriteLeaseAsync(c.One)) { } await using var reopened = await c.Containers.AcquireWriteLeaseAsync(c.One); Assert.IsFalse(Directory.EnumerateFileSystemEntries(c.Temp.Path, "*.partial-*", SearchOption.AllDirectories).Any()); Assert.IsFalse(Directory.EnumerateDirectories(c.Temp.Path, "*.staging-*", SearchOption.AllDirectories).Any()); }
    [TestMethod] public void P4StableReferenceContractRequiresCompletePortableIdentity() { var libraryId = Guid.NewGuid(); var assetId = Guid.NewGuid(); var reference = new AssetLibraryStableReference(libraryId, assetId, new string('A', 64)); Assert.AreEqual(libraryId, reference.LibraryId); Assert.AreEqual(assetId, reference.AssetId); Assert.AreEqual(new string('a', 64), reference.ContentHash); Assert.ThrowsExactly<ArgumentException>(() => new AssetLibraryStableReference(Guid.Empty, assetId, reference.ContentHash)); Assert.ThrowsExactly<ArgumentException>(() => new AssetLibraryStableReference(libraryId, assetId, "not-a-hash")); }

    private sealed class P35InjectedException : Exception;
    private sealed class Context : IDisposable
    {
        private Context(TempDirectory temp, AssetLibraryContainerDescriptor one, AssetLibraryContainerDescriptor two) { Temp = temp; One = one; Two = two; }
        public TempDirectory Temp { get; } public AssetLibraryContainerService Containers { get; } = new(); public AssetLibraryPackageService Packages { get; } = new(); public AssetLibraryMergeService Merger { get; } = new(); public AssetLibraryContainerDescriptor One { get; } public AssetLibraryContainerDescriptor Two { get; }
        public static string RepositoryRoot { get { var directory = new DirectoryInfo(AppContext.BaseDirectory); while (directory is not null && !Directory.Exists(Path.Combine(directory.FullName, "src"))) directory = directory.Parent; return directory?.FullName ?? throw new DirectoryNotFoundException(); } }
        public static async Task<Context> CreateAsync() { var temp = new TempDirectory(); var service = new AssetLibraryContainerService(); var one = await service.CreateAsync(temp.Combine("A", "中文 库一.ptlibrary"), "库一"); var two = await service.CreateAsync(temp.Combine("B", "库二.ptlibrary"), "库二"); return new(temp, one, two); }
        public static async Task InitializeAsync(string path) { await using var repository = new SqliteAssetLibraryRepository(new AssetLibraryDatabase(path)); await repository.InitializeAsync(); }
        public async Task ImportAsync(AssetLibraryContainerDescriptor library, string name, byte[] bytes, bool managed = false, bool hash = false) { var path = Temp.Combine("sources", Guid.NewGuid().ToString("N") + "-" + name); Directory.CreateDirectory(Path.GetDirectoryName(path)!); await File.WriteAllBytesAsync(path, bytes); await using var repository = new SqliteAssetLibraryRepository(new AssetLibraryDatabase(library.DatabasePath)); await repository.InitializeAsync(); await repository.ImportAsync([new AssetImportRequest(path, managed ? AssetImportMode.ManagedCopy : AssetImportMode.Reference, managed ? library.ManagedAssetsPath : null, hash)]); }
        public async Task<int> CountAsync(AssetLibraryContainerDescriptor library) { await using var repository = new SqliteAssetLibraryRepository(new AssetLibraryDatabase(library.DatabasePath)); await repository.InitializeAsync(); return (await repository.QueryAsync(new AssetLibraryQuery(PageSize: 1))).TotalCount; }
        public void Dispose() => Temp.Dispose();
    }
}
