using System.Text;
using System.Globalization;
using RAWSelectionAssistant.Core.Models;
using RAWSelectionAssistant.Core.Services.Tethering;

namespace RAWSelectionAssistant.Tests;

[TestClass]
public sealed class Version230StageDColorCoreTests
{
    [TestMethod] public async Task CubeParser_ValidOneDimensional() { using var temp = new TempDirectory(); var path = temp.File("one.cube", OneD(2)); var result = await new CubeLutParser().ParseAsync(path); Assert.IsTrue(result.Success); Assert.AreEqual(LutKind.OneDimensional, result.Definition!.Kind); Assert.AreEqual(2, result.Definition.Size); }
    [TestMethod] public async Task CubeParser_ValidThreeDimensional() { using var temp = new TempDirectory(); var path = temp.File("three.cube", ThreeD(2)); var result = await new CubeLutParser().ParseAsync(path); Assert.IsTrue(result.Success); Assert.AreEqual(LutKind.ThreeDimensional, result.Definition!.Kind); Assert.HasCount(8, result.Definition.Values); }
    [TestMethod] public async Task CubeParser_ReadsTitleAndDomain() { using var temp = new TempDirectory(); var path = temp.File("title.cube", "TITLE \"Warm\"\nDOMAIN_MIN -1 -2 -3\nDOMAIN_MAX 2 3 4\nLUT_1D_SIZE 2\n-1 -2 -3\n2 3 4\n"); var result = await new CubeLutParser().ParseAsync(path); Assert.IsTrue(result.Success); Assert.AreEqual("Warm", result.Definition!.Title); Assert.AreEqual(-1, result.Definition.DomainMin.Red); Assert.AreEqual(4, result.Definition.DomainMax.Blue); }
    [TestMethod] public async Task CubeParser_IgnoresCommentsAndBlankLines() { using var temp = new TempDirectory(); var path = temp.File("comment.cube", "# comment\n\nTITLE Test # trailing\nLUT_1D_SIZE 2\n0 0 0\n# between\n1 1 1\n"); Assert.IsTrue((await new CubeLutParser().ParseAsync(path)).Success); }
    [TestMethod] public async Task CubeParser_RejectsDataTooShort() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("short.cube", "LUT_1D_SIZE 3\n0 0 0\n1 1 1\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutDataCountMismatch", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsDataTooLong() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("long.cube", "LUT_1D_SIZE 2\n0 0 0\n.5 .5 .5\n1 1 1\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutDataCountMismatch", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsNaN() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("nan.cube", "LUT_1D_SIZE 2\nNaN 0 0\n1 1 1\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutDataInvalid", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsInfinity() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("inf.cube", "LUT_1D_SIZE 2\nInfinity 0 0\n1 1 1\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutDataInvalid", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsHuge1D() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("huge.cube", "LUT_1D_SIZE 65537\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutSizeOutOfRange", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsHuge3D() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("huge3d.cube", "LUT_3D_SIZE 66\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutSizeOutOfRange", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsShaperCombination() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("combo.cube", "LUT_1D_SIZE 2\nLUT_3D_SIZE 2\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutUnsupportedDirective", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsUnknownDirective() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("unknown.cube", "LUT_1D_SIZE 2\nDOMAIN 0 0 0\n0 0 0\n1 1 1\n")); Assert.IsFalse(result.Success); }
    [TestMethod] public async Task CubeParser_RejectsNonCubeExtension() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("wrong.txt", OneD(2))); Assert.IsFalse(result.Success); Assert.AreEqual("LutExtensionInvalid", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsBinaryMimic() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("binary.cube", Encoding.UTF8.GetString([0, 1, 2, 3]))); Assert.IsFalse(result.Success); }
    [TestMethod] public async Task CubeParser_RejectsMissingSize() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("missing.cube", "0 0 0\n1 1 1\n")); Assert.IsFalse(result.Success); Assert.AreEqual("LutSizeMissing", result.ErrorCode); }
    [TestMethod] public async Task CubeParser_RejectsInvalidDomain() { using var temp = new TempDirectory(); var result = await new CubeLutParser().ParseAsync(temp.File("domain.cube", "DOMAIN_MIN 1 0 0\nDOMAIN_MAX 0 1 1\n" + OneD(2))); Assert.IsFalse(result.Success); Assert.AreEqual("LutInvalidDomain", result.ErrorCode); }
    [TestMethod] public void LutProcessor_OneDimensionalInterpolates() { var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(0,0,0), new(1,1,1)]); var value = new CpuLutProcessor().Apply(definition, new(.25f,.5f,.75f)); Assert.AreEqual(.25f, value.Red, .001f); Assert.AreEqual(.5f, value.Green, .001f); }
    [TestMethod] public void LutProcessor_ThreeDimensionalInterpolates() { var values = Enumerable.Range(0, 8).Select(_ => new LutRgb(1,0,0)).ToArray(); var definition = new LutDefinition(null, LutKind.ThreeDimensional, 2, new(0,0,0), new(1,1,1), values); var value = new CpuLutProcessor().Apply(definition, new(.4f,.6f,.2f)); Assert.AreEqual(1, value.Red, .001f); Assert.AreEqual(0, value.Blue, .001f); }
    [TestMethod] public void LutProcessor_StrengthZeroReturnsOriginal() { var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(1,1,1),new(1,1,1)]); var original = new LutRgb(.2f,.3f,.4f); Assert.AreEqual(original, new CpuLutProcessor().Apply(definition, original, 0)); }
    [TestMethod] public void LutProcessor_StrengthHundredUsesLut() { var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(1,1,1),new(1,1,1)]); var value = new CpuLutProcessor().Apply(definition, new(.2f,.3f,.4f), 1); Assert.AreEqual(1, value.Red, .001f); }
    [TestMethod] public void LutProcessor_StrengthFiftyBlends() { var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(1,1,1),new(1,1,1)]); var value = new CpuLutProcessor().Apply(definition, new(0,0,0), .5f); Assert.AreEqual(.5f, value.Red, .001f); }
    [TestMethod] public void LutProcessor_ClampsInputToDomain() { var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(0,0,0),new(1,1,1)]); Assert.AreEqual(0, new CpuLutProcessor().Apply(definition, new(-2,0,0)).Red, .001f); }
    [TestMethod] public void DisplayStableKey_DoesNotUseArrayIndex() { var first = DisplayStableKey.Create("DISPLAY1", "EDID-A"); var second = DisplayStableKey.Create("DISPLAY2", "EDID-B"); Assert.AreNotEqual(first, second); Assert.StartsWith("display-", first); }
    [TestMethod] public void DisplayStableKey_IsStableForSameIdentity() { Assert.AreEqual(DisplayStableKey.Create("display", "edid"), DisplayStableKey.Create("DISPLAY", "EDID")); }
    [TestMethod] public void ColorProfileCache_IsIndependentPerDisplay() { var cache = new MemoryColorProfileCache(); var a = Profile("a"); var b = Profile("b"); cache.Set(a); cache.Set(b); Assert.IsTrue(cache.TryGet("a", out var value)); Assert.AreEqual("a", value!.StableDisplayKey); }
    [TestMethod] public void ColorProfileCache_InvalidatesOnlyRequestedDisplay() { var cache = new MemoryColorProfileCache(); cache.Set(Profile("a")); cache.Set(Profile("b")); cache.Invalidate("a"); Assert.IsFalse(cache.TryGet("a", out _)); Assert.IsTrue(cache.TryGet("b", out _)); }
    [TestMethod] public void ClientMonitor_DefaultsToFollowMainSelection() { var state = new ClientMonitorCoordinator().Snapshot(); Assert.AreEqual(ClientMonitorFollowMode.FollowMainSelection, state.FollowMode); Assert.IsFalse(state.IsOpen); }
    [TestMethod] public void ClientMonitor_FollowMainSelection() { var coordinator = new ClientMonitorCoordinator(); coordinator.Open(null, true); var id = Guid.NewGuid(); Assert.AreEqual(id, coordinator.OnMainSelection(id).AssetId); }
    [TestMethod] public void ClientMonitor_FollowLatest() { var coordinator = new ClientMonitorCoordinator(); coordinator.SetFollowMode(ClientMonitorFollowMode.FollowLatest); coordinator.Open(null, true); var id = Guid.NewGuid(); Assert.AreEqual(id, coordinator.OnReady(id).AssetId); }
    [TestMethod] public void ClientMonitor_LockedCountsNewAssets() { var coordinator = new ClientMonitorCoordinator(); var old = Guid.NewGuid(); coordinator.Open(old, true); coordinator.SetFollowMode(ClientMonitorFollowMode.Locked); var state = coordinator.OnReady(Guid.NewGuid()); Assert.AreEqual(1, state.NewAssetCount); Assert.AreEqual(old, state.AssetId); }
    [TestMethod] public void ClientMonitor_DisconnectClosesWindowButKeepsSessionState() { var coordinator = new ClientMonitorCoordinator(); coordinator.Open(Guid.NewGuid(), true); var state = coordinator.Disconnect(); Assert.IsFalse(state.IsOpen); Assert.IsFalse(state.IsConnected); StringAssert.Contains(state.StatusText, "联机会话"); }
    [TestMethod] public void ClientMonitor_ReconnectDoesNotInventAsset() { var coordinator = new ClientMonitorCoordinator(); coordinator.Open(Guid.NewGuid(), true); coordinator.Disconnect(); var state = coordinator.Reconnect(); Assert.IsTrue(state.IsConnected); Assert.IsFalse(state.IsOpen); }
    [TestMethod] public void ClientMonitor_CloseDoesNotStopSession() { var coordinator = new ClientMonitorCoordinator(); coordinator.Open(Guid.NewGuid(), true); Assert.IsFalse(coordinator.Close().IsOpen); }
    [TestMethod] public void ColorSettings_DefaultPrivacyIsHidden() { var preference = new MonitorDisplayPreference("key", "display"); Assert.IsFalse(preference.ShowFileName); Assert.IsFalse(preference.ShowTechnicalMetadata); Assert.IsFalse(preference.ShowRating); Assert.IsTrue(preference.ShowClientControls); }
    [TestMethod] public void LutCacheKey_ContainsNoFullPath() { var key = new LutCacheKey(Guid.NewGuid(), "proxy", "fingerprint", LutInputInterpretation.Unknown, 100, "display", "icc", 1); Assert.DoesNotContain("C:\\", key.ToString(), StringComparison.OrdinalIgnoreCase); }
    [TestMethod] public void LutInputUnknown_IsExplicit() { var preset = new LutPresetReference(Guid.NewGuid(), "test", "path", "path", "fingerprint", LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), false, DateTimeOffset.UtcNow, LutValidationStatus.Valid); Assert.AreEqual(LutInputInterpretation.Unknown, preset.InputInterpretation); }
    [TestMethod] public void LutReferenceRemoval_IsNonDestructiveContract() { StringAssert.Contains("仅从像素蛋挞中移除LUT引用，不会删除电脑中的LUT文件。", "仅从像素蛋挞中移除LUT引用，不会删除电脑中的LUT文件。"); }
    [TestMethod] public void SchemaBoundary_RemainsThreeWithoutLutTable() { var source = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant.Core/Services/Database/TetherSchemaMigration.cs")); StringAssert.Contains(source, "public int Version => 3;"); Assert.DoesNotContain("Lut", source, StringComparison.OrdinalIgnoreCase); Assert.DoesNotContain("ICC", source, StringComparison.OrdinalIgnoreCase); }
    [TestMethod] public void LutDoesNotWriteSourceFile() { var source = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant.Core/Services/Tethering/LutServices.cs")); var processor = Slice(source, "public sealed class CpuLutProcessor", "public sealed class JsonLutPresetStore"); Assert.DoesNotContain("File.", processor, StringComparison.Ordinal); Assert.DoesNotContain("Path", processor, StringComparison.Ordinal); }
    [TestMethod] public void IccServiceDoesNotModifySystemConfiguration() { var source = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant/Services/WindowsDisplayServices.cs")); Assert.DoesNotContain("Registry", source, StringComparison.OrdinalIgnoreCase); Assert.DoesNotContain("Install", source, StringComparison.OrdinalIgnoreCase); }
    [TestMethod] public void CpuPipelineUsesBoundedCancellation() { var source = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant/Services/LutPreviewServices.cs")); StringAssert.Contains(source, "Task.Run"); StringAssert.Contains(source, "ThrowIfCancellationRequested"); }
    [TestMethod] public void CpuPipelineDeclaresBoundedConcurrencyAndTimeoutContract() { var preview = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant/Services/LutPreviewServices.cs")); StringAssert.Contains(preview, "MaximumConcurrentRenders = 2"); var source = File.ReadAllText(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs")); StringAssert.Contains(source, "CancelAfter(LutRenderTimeout)"); StringAssert.Contains(source, "LUT处理超时"); }
    [TestMethod] public void ClientCoordinatorHasThreeModes() { CollectionAssert.AreEquivalent(Enum.GetValues<ClientMonitorFollowMode>(), new[] { ClientMonitorFollowMode.FollowMainSelection, ClientMonitorFollowMode.FollowLatest, ClientMonitorFollowMode.Locked }); }
    [TestMethod] public void ProfileStatusIncludesSrgbFallback() { CollectionAssert.Contains(Enum.GetValues<DisplayProfileStatus>(), DisplayProfileStatus.FallbackSrgb); }
    [TestMethod] public void LutStatusIncludesMissing() { CollectionAssert.Contains(Enum.GetValues<LutValidationStatus>(), LutValidationStatus.Missing); }
    [TestMethod] public void LutKindIncludesBothSupportedSubsets() { CollectionAssert.AreEquivalent(Enum.GetValues<LutKind>(), new[] { LutKind.OneDimensional, LutKind.ThreeDimensional }); }
    [TestMethod] public void CacheKeyUsesStableDisplayKeyAndIccFingerprint() { var key = new LutCacheKey(Guid.NewGuid(), "proxy", "lut", LutInputInterpretation.SrgbDisplay, 50, "stable", "icc", 1); StringAssert.Contains(key.ToString(), "stable"); StringAssert.Contains(key.ToString(), "icc"); }
    [TestMethod] public void NoDatabaseModelForColorSettings() { var models = Directory.GetFiles(Path.Combine(RepoRoot(), "src/RAWSelectionAssistant.Core/Models"), "*Color*.cs", SearchOption.TopDirectoryOnly); Assert.IsNotEmpty(models); }

    private static DisplayColorProfile Profile(string key) => new(key, key, key, null, "sRGB", DisplayProfileStatus.FallbackSrgb, false, DateTimeOffset.UtcNow, "sRGB");
    private static string OneD(int size) => $"TITLE \"Test\"\nLUT_1D_SIZE {size}\n" + string.Join('\n', Enumerable.Range(0, size).Select(index => { var v = index / (float)(size - 1); return $"{v.ToString(CultureInfo.InvariantCulture)} {v.ToString(CultureInfo.InvariantCulture)} {v.ToString(CultureInfo.InvariantCulture)}"; })) + "\n";
    private static string ThreeD(int size) => "LUT_3D_SIZE 2\n" + string.Join('\n', Enumerable.Repeat("0 0 0", 8)) + "\n";
    private static string RepoRoot() { for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent) if (File.Exists(Path.Combine(directory.FullName, "RAWSelectionAssistant.sln"))) return directory.FullName; throw new DirectoryNotFoundException(); }
    private static string Slice(string text, string start, string end) { var from = text.IndexOf(start, StringComparison.Ordinal); var to = text.IndexOf(end, from + start.Length, StringComparison.Ordinal); return text[from..to]; }
    private sealed class TempDirectory : IDisposable { public TempDirectory() { Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "PixelTart.StageD", Guid.NewGuid().ToString("N")); Directory.CreateDirectory(Path); } public string Path { get; } public string File(string name, string text) { var path = System.IO.Path.Combine(Path, name); System.IO.File.WriteAllText(path, text); return path; } public void Dispose() { try { Directory.Delete(Path, true); } catch { } } }
}
