using System.IO;
using System.Text.Json;

namespace RAWSelectionAssistant.WpfTests;

[TestClass]
public sealed class UiVisualRegressionTests
{
    private static string Root()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
            if (File.Exists(Path.Combine(directory.FullName, "RAWSelectionAssistant.sln"))) return directory.FullName;
        throw new DirectoryNotFoundException("RAWSelectionAssistant.sln");
    }

    [TestMethod]
    public void DiffEngine_ReportsMetricsAndSizeMismatch()
    {
        var root = Path.Combine(Path.GetTempPath(), "PixelTart-UiDiff-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root);
        try
        {
            var a = new System.Windows.Media.Imaging.WriteableBitmap(8, 8, 96, 96, System.Windows.Media.PixelFormats.Bgra32, null);
            var b = new System.Windows.Media.Imaging.WriteableBitmap(8, 8, 96, 96, System.Windows.Media.PixelFormats.Bgra32, null);
            b.WritePixels(new System.Windows.Int32Rect(2, 2, 2, 2), Enumerable.Repeat((byte)255, 16).ToArray(), 8, 0);
            Save(a, Path.Combine(root, "a.png")); Save(b, Path.Combine(root, "b.png"));
            var metrics = UiVisualDiffEngine.Compare(Path.Combine(root, "a.png"), Path.Combine(root, "b.png"), Path.Combine(root, "diff.png"));
            Assert.AreEqual(64, metrics.Width * metrics.Height); Assert.IsGreaterThan(0L, metrics.ChangedPixelCount); Assert.IsTrue(File.Exists(Path.Combine(root, "diff.png")));
            var mismatch = new System.Windows.Media.Imaging.WriteableBitmap(4, 4, 96, 96, System.Windows.Media.PixelFormats.Bgra32, null); Save(mismatch, Path.Combine(root, "small.png"));
            Assert.AreEqual("VISUAL_SIZE_MISMATCH", UiVisualDiffEngine.Compare(Path.Combine(root, "a.png"), Path.Combine(root, "small.png"), Path.Combine(root, "unused.png")).Status);
        }
        finally { Directory.Delete(root, true); }
        static void Save(System.Windows.Media.Imaging.BitmapSource bitmap, string path) { var e = new System.Windows.Media.Imaging.PngBitmapEncoder(); e.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap)); using var s = File.Create(path); e.Save(s); }
    }

    [TestMethod]
    public void BaselineGuard_RequiresExplicitApproval()
    {
        var root = Path.Combine(Root(), "tests", "UIVisual");
        Directory.CreateDirectory(Path.Combine(root, "Baselines")); Directory.CreateDirectory(Path.Combine(root, "Received")); Directory.CreateDirectory(Path.Combine(root, "Diff")); Directory.CreateDirectory(Path.Combine(root, "Reports"));
        var approved = Environment.GetEnvironmentVariable("PIXEL_TART_APPROVE_VISUAL_BASELINE") == "1";
        var baselineCount = Directory.EnumerateFiles(Path.Combine(root, "Baselines"), "*.png", SearchOption.AllDirectories).Count();
        var status = baselineCount == 0 ? "BASELINE_MISSING" : approved ? "BASELINE_APPROVAL_REQUESTED" : "BASELINE_LOCKED";
        File.WriteAllText(Path.Combine(root, "Reports", "baseline-guard.json"), JsonSerializer.Serialize(new { Status = status, BaselineCount = baselineCount, ApprovalEnvironment = "PIXEL_TART_APPROVE_VISUAL_BASELINE", Approved = approved }, new JsonSerializerOptions { WriteIndented = true }));
        if (baselineCount == 0) Assert.Inconclusive("BASELINE_MISSING: capture current UI before requesting approval.");
        Assert.IsFalse(approved, "Baseline approval is an explicit human action and must not be enabled in the default test run.");
    }

    [TestMethod]
    public void RequiredScreenMatrix_IsDeclaredWithoutPretendingCapture()
    {
        var path = Path.Combine(Root(), "docs", "evidence", "ui-guardian", "SCREENSHOT_MATRIX.json");
        if (!File.Exists(path)) Assert.Inconclusive("SCREENSHOT_MATRIX.json has not been generated by the opt-in capture.");
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        var matrix = document.RootElement.EnumerateArray().ToArray();
        Assert.HasCount(33, matrix);
        Assert.IsTrue(matrix.All(item => item.TryGetProperty("Status", out var status) && status.GetString() is "CAPTURED" or "FAILED" or "NOT_REACHABLE"));
    }
}
