using System.IO;
using System.Threading;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using RAWSelectionAssistant.Core.Models;
using RAWSelectionAssistant.Services;

namespace RAWSelectionAssistant.WpfTests;

[TestClass]
public sealed class Version230StageDColorWpfTests
{
    [TestMethod] public Task CpuPreview_OneDimensionalProcessesProxyWithoutChangingSource() => RunSta(async () => { var source = Solid(2, 1, 0, 0, 0); var before = Pixels(source); var definition = new LutDefinition(null, LutKind.OneDimensional, 2, new(0,0,0), new(1,1,1), [new(1,0,0),new(1,0,0)]); var result = await new CpuLutPreviewService().RenderAsync(source, definition, 1, null); Assert.AreEqual((byte)255, Pixels(result.Image)[2]); CollectionAssert.AreEqual(before, Pixels(source)); });
    [TestMethod] public Task CpuPreview_ThreeDimensionalProcessesProxy() => RunSta(async () => { var source = Solid(1, 1, 20, 40, 60); var definition = new LutDefinition(null, LutKind.ThreeDimensional, 2, new(0,0,0), new(1,1,1), Enumerable.Repeat(new LutRgb(0,1,0),8).ToArray()); var result = await new CpuLutPreviewService().RenderAsync(source, definition, 1, null); Assert.AreEqual((byte)255, Pixels(result.Image)[1]); });
    [TestMethod] public Task CpuPreview_StrengthZeroMatchesSource() => RunSta(async () => { var source = Solid(1,1,30,40,50); var definition = new LutDefinition(null,LutKind.OneDimensional,2,new(0,0,0),new(1,1,1),[new(1,1,1),new(1,1,1)]); var result=await new CpuLutPreviewService().RenderAsync(source,definition,0,null); CollectionAssert.AreEqual(Pixels(source),Pixels(result.Image)); });
    [TestMethod] public Task CpuPreview_HonorsCancellation() => RunSta(async () => { using var cancel=new CancellationTokenSource(); cancel.Cancel(); var definition=new LutDefinition(null,LutKind.OneDimensional,2,new(0,0,0),new(1,1,1),[new(0,0,0),new(1,1,1)]); await Assert.ThrowsExactlyAsync<TaskCanceledException>(()=>new CpuLutPreviewService().RenderAsync(Solid(20,20,1,2,3),definition,1,null,cancel.Token)); });
    [TestMethod] public Task CpuPreview_InvalidIccFallsBackSrgb() => RunSta(async () => { var source=Solid(1,1,1,2,3); var definition=new LutDefinition(null,LutKind.OneDimensional,2,new(0,0,0),new(1,1,1),[new(0,0,0),new(1,1,1)]); var profile=new DisplayColorProfile("key","display","device",Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".icc"),"missing",DisplayProfileStatus.Missing,false,DateTimeOffset.UtcNow,"sRGB"); var result=await new CpuLutPreviewService().RenderAsync(source,definition,1,profile); Assert.IsTrue(result.UsedFallback); StringAssert.Contains(result.StatusText,"sRGB"); });
    [TestMethod] public void ColorConversion_MissingProfileReturnsSameImage() { var source=Solid(1,1,1,2,3); var profile=new DisplayColorProfile("key","display","device","missing.icc","missing",DisplayProfileStatus.Missing,false,DateTimeOffset.UtcNow,"sRGB"); var result=new WpfColorConversionService().ConvertToDisplay(source,profile,out var fallback); Assert.IsTrue(fallback); Assert.AreSame(source,result); }
    [TestMethod] public async Task Cache_UsesOpaqueKeyAndDoesNotExposePaths() { using var temp=new TempDirectory(); var cache=new LutPreviewCacheService(temp.Path); var key=cache.CreateOpaqueKey(new(Guid.NewGuid(),"proxy","lut",LutInputInterpretation.Unknown,50,"display","icc",1)); Assert.HasCount(64,key); Assert.IsTrue(key.All(Uri.IsHexDigit)); Assert.DoesNotContain("proxy",key,StringComparison.Ordinal); }
    [TestMethod] public async Task Cache_StoresAndResolvesValidPng() { using var temp=new TempDirectory(); var cache=new LutPreviewCacheService(temp.Path); var key=new string('a',64); using var png=LutBitmapEncoding.EncodePng(Solid(2,2,1,2,3)); await cache.StoreAsync(key,png); Assert.IsNotNull(cache.Resolve(key)); }
    [TestMethod] public async Task Cache_CorruptFileIsRejectedAndRebuildable() { using var temp=new TempDirectory(); var key=new string('b',64); File.WriteAllBytes(Path.Combine(temp.Path,key+".png"),[1,2,3]); var cache=new LutPreviewCacheService(temp.Path); Assert.IsNull(cache.Resolve(key)); using var png=LutBitmapEncoding.EncodePng(Solid(1,1,1,2,3)); await cache.StoreAsync(key,png); Assert.IsNotNull(cache.Resolve(key)); }
    [TestMethod] public async Task Cache_LruTrimsOldest() { using var temp=new TempDirectory(); var cache=new LutPreviewCacheService(temp.Path,300); for(var index=0;index<3;index++){ using var png=LutBitmapEncoding.EncodePng(Solid(20,20,(byte)index,2,3)); await cache.StoreAsync(new string((char)('a'+index),64),png); } Assert.IsLessThanOrEqualTo(300,new DirectoryInfo(temp.Path).EnumerateFiles("*.png").Sum(file=>file.Length)); }
    [TestMethod] public async Task Cache_InvalidationNeverTouchesOutsideRoot() { using var temp=new TempDirectory(); var outside=Path.Combine(Path.GetTempPath(),"PixelTartOutside-"+Guid.NewGuid()+".txt"); await File.WriteAllTextAsync(outside,"safe"); try { await new LutPreviewCacheService(temp.Path).InvalidateAsync(_=>true); Assert.IsTrue(File.Exists(outside)); } finally { File.Delete(outside); } }
    [TestMethod] public void ClientMonitorXaml_DefaultsHidePrivateMetadata() { var xaml=Text("src/RAWSelectionAssistant/Views/ClientMonitorWindow.xaml"); Assert.DoesNotContain("SourcePath",xaml,StringComparison.Ordinal); Assert.DoesNotContain("FileName",xaml,StringComparison.Ordinal); Assert.DoesNotContain("PhotographerNote",xaml,StringComparison.Ordinal); Assert.DoesNotContain("CameraSerial",xaml,StringComparison.Ordinal); }
    [TestMethod] public void ClientMonitorXaml_HasNoFileOperations() { var text=Text("src/RAWSelectionAssistant/Views/ClientMonitorWindow.xaml")+Text("src/RAWSelectionAssistant/Views/ClientMonitorWindow.xaml.cs"); foreach(var forbidden in new[]{"删除","移动","复制","打开所在位置","输出目录","工具箱","数据库管理","File.Delete","File.Move"}) Assert.DoesNotContain(forbidden,text,StringComparison.OrdinalIgnoreCase); }
    [TestMethod] public void ClientMonitorXaml_HasFavoriteAndNoteAccessibility() { var xaml=Text("src/RAWSelectionAssistant/Views/ClientMonitorWindow.xaml"); StringAssert.Contains(xaml,"AutomationProperties.Name=\"客户收藏按钮\""); StringAssert.Contains(xaml,"AutomationProperties.Name=\"客户备注输入框\""); }
    [TestMethod] public void ClientMonitorWindow_EscapeAndF11CloseOnlyWindow() { var source=Text("src/RAWSelectionAssistant/Views/ClientMonitorWindow.xaml.cs"); StringAssert.Contains(source,"Key.Escape or Key.F11"); StringAssert.Contains(source,"Close()"); Assert.DoesNotContain("StopAsync",source,StringComparison.Ordinal); }
    [TestMethod] public void TetherWorkspace_HasLutImportSearchFavoriteDefaultsAndRelocation() { var text=TetherText(); foreach(var token in new[]{"导入 .cube","搜索LUT","收藏LUT","会话默认","项目默认","重新验证","重新定位","移除引用"}) StringAssert.Contains(text,token); }
    [TestMethod] public void TetherWorkspace_HasStrengthBeforeAfterAndSplit() { var text=TetherText(); foreach(var token in new[]{"LUT强度百分比","查看LUT前后对比","LUT分屏对比","拖动LUT分屏分割线","原图","LUT结果"}) StringAssert.Contains(text,token); }
    [TestMethod] public void TetherWorkspace_HasInputSpaceUnknownWarning() { var text=TetherText(); StringAssert.Contains(text,"输入色彩空间未知"); StringAssert.Contains(text,"不保证色彩准确"); StringAssert.Contains(text,"仅用于现场监看参考"); }
    [TestMethod] public void TetherWorkspace_HasPerDisplayIccAndDisclaimer() { var text=TetherText(); StringAssert.Contains(text,"ICC 与客户屏"); StringAssert.Contains(text,"软件不能替代显示器校准"); StringAssert.Contains(text,"回退sRGB"); }
    [TestMethod] public void TetherWorkspace_HasThreeFollowModes() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs"); foreach(var token in new[]{"跟随主选中","跟随最新","独立锁定"}) StringAssert.Contains(source,token); }
    [TestMethod] public void TetherWorkspace_HasDefaultPrivacyToggles() { var text=TetherText(); foreach(var token in new[]{"简化文件编号（默认关闭）","拍摄参数摘要（默认关闭）","显示星级（默认关闭）","允许收藏和备注"}) StringAssert.Contains(text,token); }
    [TestMethod] public void TopologyUsesStableKeyAndNotDisplayIndex() { var source=Text("src/RAWSelectionAssistant/Services/WindowsDisplayServices.cs"); StringAssert.Contains(source,"DisplayStableKey.Create"); Assert.DoesNotContain("显示器1",source,StringComparison.Ordinal); Assert.DoesNotContain("显示器2",source,StringComparison.Ordinal); }
    [TestMethod] public void TopologyChangeSafelyWithdrawsWindow() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs"); foreach(var token in new[]{"TopologyChanged","CloseClientMonitor","客户显示器未连接","Watch Folder和任务继续","可手动恢复监看"}) StringAssert.Contains(source,token); }
    [TestMethod] public void ColorPipelineLatestRequestWins() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs"); StringAssert.Contains(source,"LutRenderRequestCoordinator"); StringAssert.Contains(source,"_renderRequests.IsCurrent"); }
    [TestMethod] public void ColorPipelineFailureDoesNotStopWatchFolder() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs"); StringAssert.Contains(source,"接片继续"); Assert.DoesNotContain("StopAsync",source,StringComparison.Ordinal); }
    [TestMethod] public void ClientNotesDoNotEnterLogs() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs")+Text("src/RAWSelectionAssistant.Core/Services/Tethering/TetherMonitoringServices.cs"); Assert.DoesNotContain("ClientNote}",source,StringComparison.Ordinal); Assert.DoesNotContain("PhotographerNote}",source,StringComparison.Ordinal); }
    [TestMethod] public void NoGpuOrVendorSdkIntroduced() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs")+Text("src/RAWSelectionAssistant/Services/LutPreviewServices.cs"); foreach(var forbidden in new[]{"Direct3D","D3D11","CUDA","Edsdk","CameraRemoteSDK","MAID"}) Assert.DoesNotContain(forbidden,source,StringComparison.OrdinalIgnoreCase); }
    [TestMethod] public void NoLocalhostAndReleaseProviderNoneRemain() { var source=Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs")+Text("src/RAWSelectionAssistant/Services/WindowsDisplayServices.cs"); Assert.DoesNotContain("localhost",source,StringComparison.OrdinalIgnoreCase); StringAssert.Contains(Text("src/RAWSelectionAssistant/appsettings.license.json"),"\"Provider\": \"None\""); }

    private static BitmapSource Solid(int width,int height,byte blue,byte green,byte red){var pixels=new byte[width*height*4];for(var i=0;i<pixels.Length;i+=4){pixels[i]=blue;pixels[i+1]=green;pixels[i+2]=red;pixels[i+3]=255;}var bitmap=BitmapSource.Create(width,height,96,96,PixelFormats.Bgra32,null,pixels,width*4);bitmap.Freeze();return bitmap;}
    private static byte[] Pixels(BitmapSource source){var converted=source.Format==PixelFormats.Bgra32?source:new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);var bytes=new byte[converted.PixelWidth*converted.PixelHeight*4];converted.CopyPixels(bytes,converted.PixelWidth*4,0);return bytes;}
    private static string TetherText()=>Text("src/RAWSelectionAssistant/Views/TetherCaptureView.xaml")+Text("src/RAWSelectionAssistant/ViewModels/TetherColorViewModel.cs");
    private static string Text(string relative){for(var directory=new DirectoryInfo(AppContext.BaseDirectory);directory is not null;directory=directory.Parent)if(File.Exists(Path.Combine(directory.FullName,"RAWSelectionAssistant.sln")))return File.ReadAllText(Path.Combine(directory.FullName,relative.Replace('/',Path.DirectorySeparatorChar)));throw new DirectoryNotFoundException();}
    private static Task RunSta(Func<Task> action){var completion=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var thread=new Thread(async()=>{try{await action();completion.SetResult();}catch(Exception ex){completion.SetException(ex);}});thread.SetApartmentState(ApartmentState.STA);thread.Start();return completion.Task;}
    private sealed class TempDirectory:IDisposable{public TempDirectory(){Path=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"PixelTart.StageDWpf",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(Path);}public string Path{get;}public void Dispose(){try{Directory.Delete(Path,true);}catch{}}}
}
