param([string]$OldInstaller='', [string]$NewInstaller='', [string]$EvidenceRoot='')

$ErrorActionPreference='Stop'
$repoRoot=Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
if([string]::IsNullOrWhiteSpace($OldInstaller)){$OldInstaller=(Get-ChildItem (Join-Path $repoRoot 'artifacts\releases\2.2.0\installer') -Filter '*Setup_2.2.0_x64.exe' -File|Select-Object -First 1).FullName}
if([string]::IsNullOrWhiteSpace($NewInstaller)){$NewInstaller=(Get-ChildItem (Join-Path $repoRoot 'artifacts\releases\2.3.0\installer') -Filter '*Setup_2.3.0_RC1_x64.exe' -File|Select-Object -First 1).FullName}
if([string]::IsNullOrWhiteSpace($EvidenceRoot)){$EvidenceRoot=Join-Path $repoRoot 'artifacts\diagnostics\2.3.0\isolated-upgrade-acceptance'}
$runId=[Guid]::NewGuid().ToString('N');$runRoot=Join-Path $EvidenceRoot $runId;$localAppData=Join-Path $runRoot 'local-appdata';$installRoot=Join-Path $runRoot 'installed';$sourceRoot=Join-Path $runRoot 'source';New-Item -ItemType Directory -Force -Path $localAppData,$sourceRoot|Out-Null
$workspaceDotnet=Join-Path (Split-Path $repoRoot -Parent) '.dotnet\dotnet.exe';$dotnet=if(Test-Path -LiteralPath $workspaceDotnet){$workspaceDotnet}else{Join-Path $env:LOCALAPPDATA 'Microsoft\dotnet-sdk-10\dotnet.exe'}
$context=[ordered]@{RunId=$runId;RepoRoot=$repoRoot;OldInstaller=[IO.Path]::GetFullPath($OldInstaller);NewInstaller=[IO.Path]::GetFullPath($NewInstaller);EvidenceRoot=$runRoot;LocalAppData=$localAppData;InstallRoot=$installRoot;SourceRoot=$sourceRoot;DotnetPath=$dotnet};$contextPath=Join-Path $runRoot 'context.json';$context|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $contextPath -Encoding UTF8
Add-Type @'
using System;using System.ComponentModel;using System.Runtime.InteropServices;using System.Text;
public static class PixelTartUpgradeDesktop{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct STARTUPINFO{public int cb;public string lpReserved;public string lpDesktop;public string lpTitle;public int dwX,dwY,dwXSize,dwYSize,dwXCountChars,dwYCountChars,dwFillAttribute,dwFlags;public short wShowWindow,cbReserved2;public IntPtr lpReserved2,hStdInput,hStdOutput,hStdError;}[StructLayout(LayoutKind.Sequential)]public struct PROCESS_INFORMATION{public IntPtr hProcess,hThread;public int dwProcessId,dwThreadId;}[DllImport("user32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr CreateDesktopW(string n,string d,IntPtr m,uint f,uint a,IntPtr s);[DllImport("user32.dll")]static extern bool CloseDesktop(IntPtr d);[DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool CreateProcessW(string a,StringBuilder c,IntPtr pa,IntPtr ta,bool i,uint f,IntPtr e,string w,ref STARTUPINFO s,out PROCESS_INFORMATION p);[DllImport("kernel32.dll")]static extern uint WaitForSingleObject(IntPtr h,uint m);[DllImport("kernel32.dll")]static extern bool GetExitCodeProcess(IntPtr h,out uint c);[DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr h);public static uint Run(string n,string c,string w){var d=CreateDesktopW(n,null,IntPtr.Zero,0,0x10000000,IntPtr.Zero);if(d==IntPtr.Zero)throw new Win32Exception(Marshal.GetLastWin32Error());try{var s=new STARTUPINFO{cb=Marshal.SizeOf<STARTUPINFO>(),lpDesktop=n};PROCESS_INFORMATION p;if(!CreateProcessW(null,new StringBuilder(c),IntPtr.Zero,IntPtr.Zero,false,0x200,IntPtr.Zero,w,ref s,out p))throw new Win32Exception(Marshal.GetLastWin32Error());try{WaitForSingleObject(p.hProcess,0xffffffff);uint code;GetExitCodeProcess(p.hProcess,out code);return code;}finally{CloseHandle(p.hThread);CloseHandle(p.hProcess);}}finally{CloseDesktop(d);}}}
'@
$worker=Join-Path $PSScriptRoot 'Invoke-IsolatedUpgradeWorker.ps1';$powershell=Join-Path $PSHOME 'powershell.exe';$command=$powershell+' -NoProfile -ExecutionPolicy Bypass -File "'+$worker+'" -ContextPath "'+$contextPath+'"';$exit=[PixelTartUpgradeDesktop]::Run("PixelTartUpgrade_$runId",$command,$repoRoot);$result=Join-Path $runRoot 'result.json';if(Test-Path $result){Copy-Item $result (Join-Path $EvidenceRoot 'latest-result.json') -Force;Get-Content $result -Raw}else{@{Passed=$false;Error="Upgrade worker exited $exit"}|ConvertTo-Json|Set-Content (Join-Path $EvidenceRoot 'latest-result.json') -Encoding UTF8};if($exit-ne0){exit $exit}
